# Generated by Django 4.1.7 on 2023-05-16 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0002_company_alter_worker_worker_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epp_inspections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epp_insp_date', models.DateField(verbose_name='Fecha')),
                ('epp_insp_comments', models.TextField(max_length=500, verbose_name='Comentarios')),
                ('epp_insp_status', models.BooleanField(verbose_name='Resultado')),
                ('epp_insp_next_insp', models.DateField(verbose_name='Proxima inspección')),
                ('epp_inps_created', models.DateTimeField(verbose_name='Creado')),
                ('epp_insp_deleted', models.DateTimeField(verbose_name='Borrado')),
            ],
        ),
        migrations.CreateModel(
            name='Epp_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epp_type_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('epp_type_description', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('epp_type_insp_period', models.IntegerField(verbose_name='Período de inspección')),
                ('epp_type_cretaed', models.DateTimeField(verbose_name='Creado')),
                ('epp_type_deleted', models.DateTimeField(verbose_name='Borrado')),
            ],
        ),
        migrations.CreateModel(
            name='Epp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epp_serial_n', models.CharField(max_length=75, verbose_name='N° de serie')),
                ('epp_manufacturer', models.CharField(max_length=50, verbose_name='Marca')),
                ('epp_expire_date', models.DateField(verbose_name='Fecha de vencimiento')),
                ('epp_created', models.DateTimeField(verbose_name='Creado')),
                ('epp_deleted', models.DateTimeField(verbose_name='Borrado')),
                ('epp_assigned', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='empleados.worker', verbose_name='Empleado')),
                ('epp_insp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epp.epp_inspections')),
                ('epp_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='epp.epp_types', verbose_name='Tipo de EPP')),
            ],
        ),
    ]
