# Generated by Django 4.1.7 on 2023-05-16 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epp',
            name='epp_insp',
        ),
        migrations.AddField(
            model_name='epp_inspections',
            name='epp_inps_epp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='epp.epp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='epp',
            name='epp_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epp.epp_types', verbose_name='Tipo de EPP'),
        ),
    ]
