# Generated by Django 4.1.7 on 2023-05-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epp', '0002_remove_epp_epp_insp_epp_inspections_epp_inps_epp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epp',
            name='epp_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Borrado'),
        ),
        migrations.AlterField(
            model_name='epp_inspections',
            name='epp_insp_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Borrado'),
        ),
        migrations.AlterField(
            model_name='epp_types',
            name='epp_type_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Borrado'),
        ),
    ]
