# Generated by Django 4.1.7 on 2023-05-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epp', '0003_alter_epp_epp_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epp',
            name='epp_created',
        ),
        migrations.RemoveField(
            model_name='epp',
            name='epp_deleted',
        ),
        migrations.RemoveField(
            model_name='epp_inspections',
            name='epp_inps_created',
        ),
        migrations.RemoveField(
            model_name='epp_inspections',
            name='epp_insp_deleted',
        ),
        migrations.RemoveField(
            model_name='epp_types',
            name='epp_type_cretaed',
        ),
        migrations.RemoveField(
            model_name='epp_types',
            name='epp_type_deleted',
        ),
    ]
