# Generated by Django 4.1.7 on 2023-05-26 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_remove_company_company_created_and_more'),
        ('epp', '0004_remove_epp_epp_created_remove_epp_epp_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epp',
            name='epp_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='empleados.worker', verbose_name='Empleado'),
        ),
    ]
