# Generated by Django 4.1.7 on 2023-05-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epp', '0005_alter_epp_epp_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='epp',
            name='epp_next_insp_date',
            field=models.DateField(default='1900-01-01', verbose_name='Fecha proxima inspección'),
        ),
    ]
