# Generated by Django 4.1.7 on 2023-05-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_alter_worker_worker_company'),
        ('epp', '0006_epp_epp_next_insp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epp',
            name='epp_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='worker_related', to='empleados.worker', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='epp',
            name='epp_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epp_type_related', to='epp.epp_types', verbose_name='Tipo de EPP'),
        ),
        migrations.AlterField(
            model_name='epp_inspections',
            name='epp_inps_epp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epp_related', to='epp.epp'),
        ),
    ]
