# Generated by Django 4.1.7 on 2023-05-29 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epp', '0009_alter_epp_inspections_epp_insp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epp_inspections',
            name='epp_insp_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 29, 19, 42, 18, 581979), verbose_name='Fecha'),
        ),
    ]
