# Generated by Django 4.1.7 on 2023-05-30 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epp', '0010_alter_epp_inspections_epp_insp_date'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='epp_inspections',
            name='epp_insp_date',
            field=models.DateField(("Date"), auto_now_add=True))
    ]
