# Generated by Django 4.1.7 on 2023-05-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epp', '0011_rename_epp_inps_epp_epp_inspections_epp_inps_epp_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epp_inspections',
            old_name='epp_inps_epp',
            new_name='epp_inps_epp_id',
        ),
        migrations.AlterField(
            model_name='epp_inspections',
            name='epp_insp_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
