# Generated by Django 4.1.7 on 2023-05-30 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epp', '0013_alter_epp_inspections_epp_insp_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epp_inspections',
            old_name='epp_inps_epp_id',
            new_name='epp_inps_epp',
        ),
    ]
