# Generated by Django 4.1.7 on 2023-05-14 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=25, verbose_name='Compañia')),
                ('company_descript', models.TextField(max_length=250, verbose_name='Descripción')),
                ('company_address', models.CharField(max_length=250, verbose_name='Dirección')),
                ('company_created', models.DateTimeField(verbose_name='Creado')),
                ('company_deleted', models.DateTimeField(blank=True, null=True, verbose_name='Borrado')),
            ],
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_created',
            field=models.DateTimeField(verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_deleted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Borrado'),
        ),
    ]
