# Generated by Django 4.1.7 on 2023-05-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_worker_worker_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='worker_birthday',
            field=models.DateField(default='1900-01-01', verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='worker',
            name='worker_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
    ]
