# Generated by Django 4.1.7 on 2023-05-18 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_worker_worker_birthday_worker_worker_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_descript',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_comments',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.company', verbose_name='Empresa'),
        ),
    ]
