# Generated by Django 4.1.7 on 2023-05-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_alter_company_company_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_created',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_deleted',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='worker_created',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='worker_deleted',
        ),
    ]
