# Generated by Django 4.1.7 on 2023-05-28 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0006_remove_company_company_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_related', to='empleados.company', verbose_name='Empresa'),
        ),
    ]
