# Generated by Django 4.1.7 on 2023-06-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_alter_worker_worker_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certif_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('certif_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Decsripción')),
            ],
            options={
                'ordering': ['certif_name'],
            },
        ),
        migrations.AddField(
            model_name='worker',
            name='worker_certifications',
            field=models.ManyToManyField(blank=True, null=True, to='empleados.certification', verbose_name='Certificaciones'),
        ),
    ]
