# Generated by Django 4.1.7 on 2023-06-17 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_certification_worker_worker_certifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='worker_certifications',
            field=models.ManyToManyField(blank=True, null=True, related_name='Certification', to='empleados.certification', verbose_name='Certificaciones'),
        ),
        migrations.CreateModel(
            name='worker_certif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certif_expire', models.DateField(verbose_name='Fecha vencimiento')),
                ('certif_if', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cert_id', to='empleados.certification', verbose_name='Certif')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Worker_id', to='empleados.worker', verbose_name='Empleado')),
            ],
            options={
                'ordering': ['certif_expire'],
            },
        ),
    ]
